## YAML Template.
---
services:
    zuri.demo.controller:
        class: zuri\demo\controller\main
        arguments:
            - @config
            - @cotroller.helper
            - @template
            - @user
